# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fe7764e4255a47e80ca159ab45cb4ad7c645e0275e113f5aa863cb7ef01b3fceb33f84bba65579924823ca212b406f267ae2ec028a7c667b4bf1f822fb67d11

test:
  secret_key_base: 712e26ea34ceff425b1c234b7857c94b0d49a7d8e5a9b6cb2c8334f5a5aa7b7f6afa22e43d6896a7a4c6f72e7acc914627d44277be4f5e29ba463876b7d0b2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
